version: "3.8"
services: 
  nginx: 
    container_name: nginx_1
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - service_1 

  service_1: 
    container_name: service_1
    build: ./service_1
    depends_on: 
    - service_2
    - service_3 

  service_2: 
    container_name: service_2
    build: ./service_2


  service_3:
    container_name: service_3 
    build: ./service_3

  service_4:
    container_name: service_4
    build: ./service_4
    depends_on:
    - service_1